#!/bin/sh
# check users by "cat
echo "Please provide username to be deleted. If need be, check users with in file /etc/passwd"
read USER_NAME
if [ -n "$USER_NAME" ]
then
    sudo deluser --remove-home $USER_NAME
else
    exit
fi